- hosts: webservers
  gather_facts: no
  tasks:
    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
      become: yes
      when: ansible_distribution == "Ubuntu"

    - name: delete git config
      ansible.builtin.file:
        path: "/home/{{ item }}/.gitconfig"
        state: absent
      loop:
        - jaime
        - sansa
        - robert
      become: yes