- hosts: webservers
  gather_facts: no
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags: config

    - name: install git
      ansible.builtin.apt: 
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: install
      when: ansible_distribution == "Ubuntu"

    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - jaime
        - sansa
        - robert

    - name: copy git config
      ansible.builtin.template:
        src: templates/.gitconfig.j2
        dest: "/home/{{ item }}/.gitconfig"
      loop:
        - jaime
        - sansa
        - robert
      become: yes