- hosts: webservers
  gather_facts: no
  tasks:
    - name: install git
      ansible.builtin.apt: 
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: install
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags: config